<?php
namespace AppBundle\ThriftModel;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


final class State {
  const STATE_ZERO = 0;
  const STATE_UN = 1;
  static public $__names = array(
    0 => 'STATE_ZERO',
    1 => 'STATE_UN',
  );
}

class Test extends TBase {
  static $_TSPEC;

  public $id = null;
  public $content = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'id',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'content',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Test';
  }

  public function read($input)
  {
    return $this->_read('Test', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('Test', self::$_TSPEC, $output);
  }
}

class InvalidValueException extends TException {
  static $_TSPEC;

  public $error_code = null;
  public $error_msg = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'error_code',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'error_msg',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'InvalidValueException';
  }

  public function read($input)
  {
    return $this->_read('InvalidValueException', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('InvalidValueException', self::$_TSPEC, $output);
  }
}


